name: Deploy
on:
  workflow_run:
    workflows: ["Lint"]
    branches: ["master", "main"]
    types:
      - completed
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: GItHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Export pinned requirements
        run: |
          uv export --format requirements-txt -o /tmp/requirements.txt --no-dev

      - name: install dependencies
        run: |
          mkdir build
          uv pip install -r /tmp/requirements.txt --target=build
          cp src/FeedSummarizer/lambda_function.py build/
          zip -r ./lambda.zip ./build

      - name: lambda update
        run: |
          aws lambda update-function-code --function-name FeedSummarizer --zip-file fileb://lambda.zip --region "us-east-1" > /dev/null 2>&1
