name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: GItHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir package
          pip install -r src/feed_summarizer/requirements.txt ./package

      - name: create deployment package
        run: |
          cd package
          zip -r9 ../package.zip .
          cd ..
          zip -rg package.zip src/feed_summarizer/

      - name: lambda update
        run: |
          pip3 install awscli
          cd src/feed_summarizer && zip -r package.zip ./*
          aws lambda update-function-code --function-name FeedSummarizer --zip-file fileb://package.zip --publish
